. Ok, it was an issue wuth the import, need to destructure the export from root binding. Now we are getting the expected not implement error (Which is actually an error because that is not defined 🤭)
    bubblescript 🍀 npx mocha test/definir.js

      definir
	1) sets a constant

      0 passing (36ms)
      1 failing

      1) definir
	   sets a constant:
	 ReferenceError: NotImplementedError is not defined
	  at Object.<anonymous> (src/root_binding.js:107:5)
	  at SpecialForm.call (src/special_form.js:25:20)
	  at Fn.call (src/fn.js:41:15)
	  at evalList (src/eval.js:126:15)
	  at evalExpression (src/eval.js:93:14)
	  at LazyList.tryEach (src/abstract_list.js:156:20)
	  at evalEach (src/eval.js:77:15)
	  at ėval (src/eval.js:46:12)
	  at Context.<anonymous> (test/definir.js:12:9)
	  at process.processImmediate (node:internal/timers:505:21)
	  en (::)