.
bubblescript 🍀 bin/bubls 🍕
¡Hola, Mucho Gusto, Ron Burgandy!
bubblescript 🍀 cat 🍕 | bin/bubls
%< : { puts } (require "core")
true
%< : 👋 "¡Hola, Mucho Gusto, Ron Burgandy!"
¡Hola, Mucho Gusto, Ron Burgandy!
%< puts 👋
¡Hola, Mucho Gusto, Ron Burgandy!
undefined
%<
TypeError: Cannot read properties of undefined (reading 'isEmpty')
    at EmptyList.tryEach (file:///data/data/com.termux/files/home/bubblescript/%E2%98%95%EF%B8%8F/list.js:145:19)
    at evalEach (file:///data/data/com.termux/files/home/bubblescript/%E2%98%95%EF%B8%8F/eval.js:77:15)
    at ėval (file:///data/data/com.termux/files/home/bubblescript/%E2%98%95%EF%B8%8F/eval.js:39:12)
    at file:///data/data/com.termux/files/home/bubblescript/bin/bubls:60:22
    at [_onLine] [as _onLine] (node:internal/readline/interface:463:7)
    at [_line] [as _line] (node:internal/readline/interface:953:18)
    at [_ttyWrite] [as _ttyWrite] (node:internal/readline/interface:1478:24)
    at Socket.onkeypress (node:internal/readline/interface:284:20)
    at Socket.emit (node:events:508:28)
    at emitKeys (node:internal/readline/utils:371:14)
%< (new Array 1 2 3)
1,2,3