. require list
This was nagging me. I was stracting my head. Why was i getting an error
when i tried to explictly require List through the module system.

Doing so was unnessecary, but still, it should have been possible. Not
neccessary because List is alreasy being added to the main binding for
convience. Anyway, a best pratice would be to explictly require it
regardless, and even though the binding has it up the prototype chain,
there should a problem setting it in the current context/binding.

So, turns pit, the issue obviosly, list exports an object that has to be
destructured. Oops,. You probably already knew that, but it can be easy
to forget when ypu are jumping around and juggling different things. The
error message, which i'll include below, wasn't much help. Hopefully we
get some improved error handeling, and thiz would be a good case to
ponder for that. Anyway, it wasn't to hard to debug, but i did have to
go into the js to play with debug statements. As a good developer
experince, we would desire that bubblescript users wouldn't have too.
That i suppose, is when we would know that we have a stable platform for
people to devekop on. Until then, i suppose we are still ecperimental.

bubblescript 🍀 bin/🫧 🌟/🧪 🫧/list.🫧
file:///data/data/com.termux/files/home/bubblescript/%E2%98%95%EF%B8%8F/binding.js:358
    return recipient[message](...params);
                             ^

TypeError: recipient[message] is not a function
    at send (file:///data/data/com.termux/files/home/bubblescript/%E2%98%95%EF%B8%8F/binding.js:358:30)
    at Fn.call (file:///data/data/com.termux/files/home/bubblescript/%E2%98%95%EF%B8%8F/fn.js:32:16)
    at evalList (file:///data/data/com.termux/files/home/bubblescript/%E2%98%95%EF%B8%8F/eval.js:145:23)
    at evalList (file:///data/data/com.termux/files/home/bubblescript/%E2%98%95%EF%B8%8F/eval.js:137:22)
    at evalExpression (file:///data/data/com.termux/files/home/bubblescript/%E2%98%95%EF%B8%8F/eval.js:88:14)
    at List.tryEach (file:///data/data/com.termux/files/home/bubblescript/%E2%98%95%EF%B8%8F/list.js:157:16)
    at ėval.evalEach (file:///data/data/com.termux/files/home/bubblescript/%E2%98%95%EF%B8%8F/eval.js:72:15)
    at Fn.call (file:///data/data/com.termux/files/home/bubblescript/%E2%98%95%EF%B8%8F/fn.js:47:17)
    at Fn.call (file:///data/data/com.termux/files/home/bubblescript/%E2%98%95%EF%B8%8F/fn.js:37:15)
    at evalList (file:///data/data/com.termux/files/home/bubblescript/%E2%98%95%EF%B8%8F/eval.js:145:23)

Node.js v25.3.0