. Not quite ready to use the bubblenative each function, which has a bug. Have it 's invokation commented out for now and namespeced to lista.
bubblescript 🍀 npm run 🧪🫧
> bubblescript@0.1.6.⛄️.testing 🧪🫧
> bin/🫧 🌟/🧪 🧪/*.🫧

Loading: undefined
node:internal/modules/run_main:107
    triggerUncaughtException(
    ^

Error: ENOENT: no such file or directory, open '/data/data/com.termux/files/home/bubblescript/undefined'
    at Object.readFileSync (node:fs:434:20)
    at syncLoad (file:///data/data/com.termux/files/home/bubblescript/%E2%98%95%EF%B8%8F/load.js:24:19)
    at Object.require (file:///data/data/com.termux/files/home/bubblescript/%E2%98%95%EF%B8%8F/binding.js:352:5)
    at evalList (file:///data/data/com.termux/files/home/bubblescript/%E2%98%95%EF%B8%8F/eval.js:120:24)
    at evalExpression (file:///data/data/com.termux/files/home/bubblescript/%E2%98%95%EF%B8%8F/eval.js:91:14)                                                         at List.tryEach (file:///data/data/com.termux/files/home/bubblescript/%E2%98%95%EF%B8%8F/list.js:144:20)
    at List.tryEach (file:///data/data/com.termux/files/home/bubblescript/%E2%98%95%EF%B8%8F/list.js:147:23)
    at ėval.evalEach (file:///data/data/com.termux/files/home/bubblescript/%E2%98%95%EF%B8%8F/eval.js:75:15)
    at Fn.call (file:///data/data/com.termux/files/home/bubblescript/%E2%98%95%EF%B8%8F/fn.js:46:17)            at Fn.call (file:///data/data/com.termux/files/home/bubblescript/%E2%98%95%EF%B8%8F/fn.js:38:15)            en (🌟/🧪:44:9)
    en (/data/data/com.termux/files/home/bubblescript/🫧/lista.🫧:38:9)
    en (/data/data/com.termux/files/home/bubblescript/🫧/lista.🫧:38:3)                                         en (🌟/🧪:42:7) {                                   errno: -2,
  code: 'ENOENT',                                       syscall: 'open',
  path: '/data/data/com.termux/files/home/bubblescript/undefined'
}
                                                      Node.js v25.3.0