. Add new test to cover functionality that was orginally being tested under ėval, but was actually consuming evalEach, which was previously named ëval. Two test passing now, still 8 to go. test/eval.js
    bubblescript 🍀 npx mocha test/eval.js

      evalEach
	✔ evaluates a keyword

      ėval
	✔ evaluates a keyword
	1) runs script top to bottom
	2) evaluates BubbleScript
	3) can console.log
	4) evaluates a vektar with ease
	5) expands a macro
	6) expands a more complex macro
	function parameters
	  7) splats
	  8) destructures
	  - splats for outbound functions
	  - splats for inbound functions

      2 passing (70ms)
      2 pending
      8 failing

      1) ėval
	   runs script top to bottom:
	 TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
	  at new Tökenizer (src/tökenize.js:17:26)
	  at tokenize (src/tökenize.js:305:10)
	  at parse (src/parse.js:31:25)
	  at ėval (src/eval.js:46:30)
	  at Context.<anonymous> (test/eval.js:43:5)
	  at process.processImmediate (node:internal/timers:505:21)

      2) ėval
	   evaluates BubbleScript:
	 TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
	  at new Tökenizer (src/tökenize.js:17:26)
	  at tokenize (src/tökenize.js:305:10)
	  at parse (src/parse.js:31:25)
	  at ėval (src/eval.js:46:30)
	  at Context.<anonymous> (test/eval.js:53:18)
	  at process.processImmediate (node:internal/timers:505:21)

      3) ėval
	   can console.log:
	 TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
	  at new Tökenizer (src/tökenize.js:17:26)
	  at tokenize (src/tökenize.js:305:10)
	  at parse (src/parse.js:31:25)
	  at ėval (src/eval.js:46:30)
	  at Context.<anonymous> (test/eval.js:58:5)
	  at process.processImmediate (node:internal/timers:505:21)

      4) ėval
	   evaluates a vektar with ease:
	 TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
	  at new Tökenizer (src/tökenize.js:17:26)
	  at tokenize (src/tökenize.js:305:10)
	  at parse (src/parse.js:31:25)
	  at ėval (src/eval.js:46:30)
	  at Context.<anonymous> (test/eval.js:63:18)
	  at process.processImmediate (node:internal/timers:505:21)

      5) ėval
	   expands a macro:
	 TypeError: ast.evalEach is not a function
	  at Context.<anonymous> (test/eval.js:87:9)
	  at process.processImmediate (node:internal/timers:505:21)

      6) ėval
	   expands a more complex macro:
	 TypeError: ast.evalEach is not a function
	  at Context.<anonymous> (test/eval.js:136:9)
	  at process.processImmediate (node:internal/timers:505:21)

      7) ėval
	   function parameters
	     splats:
	 TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
	  at new Tökenizer (src/tökenize.js:17:26)
	  at tokenize (src/tökenize.js:305:10)
	  at parse (src/parse.js:31:25)
	  at ėval (src/eval.js:46:30)
	  at Context.<anonymous> (test/eval.js:155:20)
	  at process.processImmediate (node:internal/timers:505:21)

      8) ėval
	   function parameters
	     destructures:
	 TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
	  at new Tökenizer (src/tökenize.js:17:26)
	  at tokenize (src/tökenize.js:305:10)
	  at parse (src/parse.js:31:25)
	  at ėval (src/eval.js:46:30)
	  at Context.<anonymous> (test/eval.js:172:20)
	  at process.processImmediate (node:internal/timers:505:21)