. Everything looks good from what i can see, but...
...evaualtion complains describir is not a function.

Also, kind of weird, when using console to debug and
print the vaule of describir, getting a double
render. Might be related to the test runner, because
i wasn't getting double output when printing from the
fuente/apoyo/moca.js

bubblescript 🍀 node --version
v24.7.0

bubblescript 🍀 npx mocha prueba/símbolos/fn.js
 Exception during run: ReferenceError: Cannot access 'Moca' before initialization
    at Object.<anonymous> (/data/data/com.termux/files/home/bubblescript/fuente/apoyo/moca.js:6:35)
    at Module._compile (node:internal/modules/cjs/loader:1738:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1871:10)
    at Module.load (node:internal/modules/cjs/loader:1470:32)
    at Module._load (node:internal/modules/cjs/loader:1290:12)                                                  at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:238:24)
    at Module.require (node:internal/modules/cjs/loader:1493:12)                                                at require (node:internal/modules/helpers:152:16)
    at Object.<anonymous> (/data/data/com.termux/files/home/bubblescript/prueba/símbolos/fn.js:6:17)
    at Module._compile (node:internal/modules/cjs/loader:1738:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1871:10)
    at Module.load (node:internal/modules/cjs/loader:1470:32)
    at Module._load (node:internal/modules/cjs/loader:1290:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)                                               at wrapModuleLoad (node:internal/modules/cjs/loader:238:24)
    at cjsLoader (node:internal/modules/esm/translators:317:5)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:209:7)
    at ModuleJob.run (node:internal/modules/esm/module_job:371:25)                                              at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:683:26)
    at async formattedImport (/data/data/com.termux/files/home/bubblescript/node_modules/mocha/lib/nodejs/esm-utils.js:9:14)
    at async Object.requireModule [as requireOrImport] (/data/data/com.termux/files/home/bubblescript/node_modules/mocha/lib/nodejs/esm-utils.js:97:28)
    at async exports.loadFilesAsync (/data/data/com.termux/files/home/bubblescript/node_modules/mocha/lib/nodejs/esm-utils.js:123:20)
    at async singleRun (/data/data/com.termux/files/home/bubblescript/node_modules/mocha/lib/cli/run-helpers.js:164:3)
    at async exports.handler (/data/data/com.termux/files/home/bubblescript/node_modules/mocha/lib/cli/run.js:379:5)