. Getting closer. Turns out we weren't defining our emoji functions, and we aren't/weren't raising any exception on undefined function invokation. Might have some of that worked out. This is an interesting error, looks like we might be getting half an emoji. Need to look qt it furthure and figure out what is going on. My spydi senses maje me think it might have something to do with where we recurse in each.
On correction, could likly have someting to do with the at method, or
pop and the [] for index look up. This would be a vote to inheriate
abstract list from array as we were attempting, for elegance, but should
be easy to make work with o and oo by implementing at. Which ever, but
nice added points for using array because it should just work correctly
if this is the case.

bubblescript 🍀 npm run 🧪🫧

> bubblescript@0.1.6.⛄️.testing 🧪🫧                  > bin/🫧 🌟/🧪 🧪/*.🫧
Loading: 🧪/array.🫧
Loading: �
node:internal/modules/run_main:107
    triggerUncaughtException(
    ^

Error: ENOENT: no such file or directory, open '/data/data/com.termux/files/home/bubblescript/�'                at Object.readFileSync (node:fs:434:20)               at syncLoad (file:///data/data/com.termux/files/home/bubblescript/%E2%98%95%EF%B8%8F/load.js:24:19)
    at Object.require (file:///data/data/com.termux/files/home/bubblescript/%E2%98%95%EF%B8%8F/binding.js:352:5)
    at evalList (file:///data/data/com.termux/files/home/bubblescript/%E2%98%95%EF%B8%8F/eval.js:120:24)
    at evalExpression (file:///data/data/com.termux/files/home/bubblescript/%E2%98%95%EF%B8%8F/eval.js:91:14)                                                         at List.tryEach (file:///data/data/com.termux/files/home/bubblescript/%E2%98%95%EF%B8%8F/list.js:144:20)    at List.tryEach (file:///data/data/com.termux/files/home/bubblescript/%E2%98%95%EF%B8%8F/list.js:147:23)    at ėval.evalEach (file:///data/data/com.termux/files/home/bubblescript/%E2%98%95%EF%B8%8F/eval.js:75:15)    at Fn.call (file:///data/data/com.termux/files/home/bubblescript/%E2%98%95%EF%B8%8F/fn.js:46:17)            at Fn.call (file:///data/data/com.termux/files/home/bubblescript/%E2%98%95%EF%B8%8F/fn.js:38:15)
    en (🌟/🧪:44:9)                                       en (/data/data/com.termux/files/home/bubblescript/🫧/lista.🫧:42:9)                                         en (/data/data/com.termux/files/home/bubblescript/🫧/lista.🫧:42:3)                                         en (/data/data/com.termux/files/home/bubblescript/🫧/lista.🫧:44:9)
    en (/data/data/com.termux/files/home/bubblescript/🫧/lista.🫧:44:3)                                         en (🌟/🧪:42:7) {                                   errno: -2,
  code: 'ENOENT',                                       syscall: 'open',
  path: '/data/data/com.termux/files/home/bubblescript/�'
}
Node.js v25.3.0